### PR TITLE
Modified qstat-pretty to work with Torque Resource Manager

### PR DESCRIPTION
**Pull request by muppetjones**
A few changes:
- Modified to work with Torque Resource Manager (**_instead of**_ GridEngine)
  - `-x` vs `-xml`
  - changed names of xml fields
- Added "Professional" table format (no vertical delimiters)
- Added `fit_table` (vs. `grow_table`)--dynamically sizes the table to the appropriate size based on column sizes, and modifies delimiters (suggested space only!) to pad column spacing if space is available.
- Modified `state_color` to be slightly more efficient and cleaner.

Tested on Python 2.7.6 and 3.4.3

### CODE REVIEW

**Comment by sseemayer** [comment]
Thanks for the pull request! Is there any way that you could split up your commits into a part that is generally applicable to qstat-pretty and a fork specific to Torque? That way, GridEngine users would benefit from the pull request, too. Alternatively, we could have multiple parsers to support Torque and GridEngine in the same project.

**Comment by muppetjones** [comment]
Sure thing.

Any thoughts on the best way to split the parsers? My initial thought is to parse `qstat --help` for `[-x]` vs `[-xml]` and use that to select which parser to use.

**Comment by sseemayer** [comment]
Since I'm now working at an institute that uses Platform LSF instead of GridEngine or Torque, it's not easy for me to test any suggestion of my own. I'd leave this decision in your able hands :)

**Comment by sseemayer** [comment]
Another idea would be to have a command line argument to set the qstat dialect plus a configuration file to configure a default source of job data.

**Comment by muppetjones** [comment]
I'll work on it. Personal preference would be automatic detection to simplify things, but having the ability to add a different configuration via CLI would make it much more versatile.

I'll try to get it hashed out over the next week or so.

**Comment by muppetjones** [comment]
The latest commits add a GPLv2 license (I'm very open to changing if you would prefer a different license) and adds a few fixes, including _some_ automatic detection of the resource manager.

The code is only tested with Torque as I don't have access to GridEngine at the moment, but it checks for Torque then defaults to GridEngine. The implementation is rough, and could certainly use improvement, but it works so far for me.

**Comment by sseemayer** [comment]
Thanks a lot for this! I have no way of testing this on GridEngine either but there can always be another bug report :)

**Comment by muppetjones** [comment]
No problem 8^]. Thanks for writing it in in the first place. Note: I just fixed a bug that had cropped up. Do I need to do another pull request? How is that handled?

**Comment by sseemayer** [comment]
Not sure, I would say if it belongs to the changes in this PR do it her, otherwise open a new one.

**Pull request merged**
